// require('./spec/debug.spec.js');
require('./spec/mixed.spec.js');
require('./spec/datetime.spec.js');
require('./spec/numeric.spec.js');
require('./spec/hex.spec.js');
require('./spec/unicode.spec.js');
require('./spec/hex.spec.js');
require('./spec/ip.spec.js');
require('./spec/version.spec.js');
require('./spec/filename.spec.js');
require('./spec/space.spec.js');
require('./spec/sparse.spec.js');
require('./spec/insensitive.spec.js');
require('./spec/desc.spec.js');
require('./spec/rosetta.spec.js');
require('./spec/contributed.spec.js');
